#!/bin/bash

# <xbar.title>bitping/track/graph</xbar.title>
# <xbar.version>v1.0</xbar.version>
# <xbar.author>Jeffrey Urban</xbar.author>
# <xbar.author.github>JeffreyUrban</xbar.author.github>
# <xbar.desc>Based on bitping by Simon Hudson (SimonSays13), but switched to check status via Tailscale for energy
# efficiency, added support for sending wake up request to wake-on-lan server, and removed ping stats/graphs.
# Shows status of the remote server via local or tailscale hostname. .</xbar.desc>
# <xbar.dependencies></xbar.dependencies>
# <xbar.abouturl>http://www.provulo.com/</xbar.abouturl>

# This is a plugin for Bitbar
# https://github.com/matryer/bitbar
#
# Author: (Jeffrey Urban) Jeffrey@JeffreyUrban.com
# Based on bitping by Simon Hudson; based on original bitbar ping by Trung Đinh Quang, Grant Sherrick and Kent Karlsson.
# Includes bitbash code by GaneshV to render bitmap to menu ( https://github.com/ganeshv )
# Theme from http://colorbrewer2.org/

# Menu Bar Icon

if /Applications/Tailscale.app/Contents/MacOS/Tailscale status | grep 'rig' | grep 'offline' > /dev/null; then

    # binary of png image for system down, generated by `base64 -i ../rig-down.png`
    echo "| image='iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAAGKADAAQAAAABAAAAGAAAAADB/VeXAAAB80lEQVRIDd2VvS5EQRTHd62vAoWIQrkKFKIgEokodHT7ACKS1YhW4QUU3kG29AQqlUg2IiqREIlGIbGI2Ihvrt//7tzN3LljXTpO8tszc+bMnDPnMDeT+euSTXOBIAjG8ZsB2z9gfg6b2Wz2Ce2VZq81aezHNAs6VEGkm2AA5klgmSBHjBNiZ1RfZMMokwnIgQ77SsZYmINbWCHIhuuYCMDhwziVoR2e3Q3O/JW5aIMuKLpBfCUawrEDVJIDSCN9OCmpJYjdwhcgKkmFbK7SnM6t1Y93kI5JwmCt5tjYCi0wBXmtuXPjr16p3B9mXle+ANEN5PQGC7AD2yBx5zVr7dfeG1p8JVImoVCiDzI+ZnII+zVrxp0bc6gSCfsC2BsyBNnFMBIZ3XlkN7qeXGRPRIwWpMk+bQ9Cd37Ui5j4Ath1/GkPEjdoWKJf9CBVgJiTW3N3btVD++zbh0u+EkUBHq3N3w0fzOF6XmLiK9Gd8VilyaeMW0CJ6M3RWP9M6k0rKOMX6IVO2ILGwqFtsAZnILmEk3BEQPS1GWv93Iwv0CXobny6tYrzMEgWq9VqD1oHl6AIkkHQEyIpWFvTDdmUhweogjKUrEMhHAVBBX1jxtNfnRo1NLHORq3pg6KnWD3Qt2EP7mES9P5L9LEp89elHv1D+QRmsSHelx+iVwAAAABJRU5ErkJggg=='"

else

    # binary of png image for system up, generated by `base64 -i ../rig-up.png`
    echo "| image='iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAAGKADAAQAAAABAAAAGAAAAADB/VeXAAADM0lEQVRIDd1US0hUURg+j3uvM2M66tiYo5MtNFOSkEQw2lgS2CYIJFy0CMJFaBjVomWrVi2KIigqdy1cuAhXPUhLCZIESUxDwdIcX6Mzo/O659F/1TvqvU7Otv5hzjn/8zv/41yE/nXCmSRw5ldHfcDFm/PiGtaQgJ+CokpSOhj6WT6x9qqrsSueLk5GAPWBjtYFp+j0xqnkCGFJBOyYRBRZSSQargyS9t7yh9/2AtkT4Nz09ZNLTtngYpgKgqXpSIR52twhl7rRHHnZw9BKaRTd7i959Hy3BdzGKmiabK9ZcuNBhrFDkThh1bNtPFBJnQiiS0yylrRkbnVIufrO/2AXiGINQDGpmtf4gaqgOO/R40NWPUKHdogCG+cYzfeJPDIoJb4Ggr8DCKpLJ6dIwWihu+Ll4o5oaY/H51uhkAc5loJYjWwZmAaYK7RltEXLj+XLYZ/a4NZjM2/LXky1DbWpO3nDvjjhoYsUY4aFpUsI2RB1KlJN7a7uZuM+euVLIe8LOl1vjGBW3pCZBPdP+ZoyG4DKCU6lhWHkERoriaojVOD3W05WHi2BAm6PNKbY4qVimYga1+AI075Ffb4nH+F4YjYNb4gL4b8oITbmtqm0ARgOzFiAMu3BZgZSSoTppuf2aksJHk+qjpn2wMjAIL5HBjaA7eKAR4Y92IgOCzzM/UtEEAGjbZhMemAAGMEFgipZyJYBg3kwbBwJJWaxTcvqfCaawExCAxxWI1uTs7kSCipJFHDTO6dmOyfgZatSUAI30ZnCVBhXAfdkSFKNwdxncZKMKtI7pyVz/Fjp3RfgMBIfakNZ95az2KVJp2g9GlUX4Ju6EtRQZUGS/oBnUjDuYp5j62gKvtjqYE7SXxtT5yqipCuC125aAWxNMQ0ujN2oGS/SR4oioq1xwNvTezb4XWX4tSbYQNBJnpX91qqwg3m/FrG+I2F08ZP/cY/pu3O3lchUMhpfz9bVWMRF7/c2rd6ddnJP1aq2SDhaDqoCqUV6PwwE1QSGsVBCpp91T5sBPBvcPHWrLpyt+6TgBGYrIVj8c2k4vBZye04vqDjXCFYcdaz4l9cHn9Y91a3B/w/+D7JwenxV20wbAAAAAElFTkSuQmCC'"

fi

# Menu entries
# Replace `rig` with the device name configured on your Wake-on-LAN server.
# Replace `your-wol-server` with your server hostname.
# Replace `username` with your username.

echo "---"

# Menu entry
echo "Wake rig | bash='curl' param1='-s' param2='http://your-wol-server:8000/wake?device=rig' terminal=false"

echo "---"

# Menu entry
echo 'Suspend rig | bash="/usr/bin/ssh" param1="-i" param2="/Users/username/.swiftbar/ssh/id_<rig>-suspend" param3="username@rig" param4="/usr/bin/sudo /usr/bin/systemctl suspend" terminal=false'

echo "---"

# Menu entry
echo 'Poweroff rig | bash="/usr/bin/ssh" param1="-i" param2="/Users/username/.swiftbar/ssh/id_<rig>-poweroff" param3="username@rig" param4="/usr/bin/sudo /usr/bin/systemctl poweroff" terminal=false'

echo "---"

# Menu entry
echo 'Reboot rig | bash="/usr/bin/ssh" param1="-i" param2="/Users/username/.swiftbar/ssh/id_<rig>-reboot" param3="username@rig" param4="/usr/bin/sudo /usr/bin/systemctl reboot" terminal=false'
